# Generated by Django 5.1 on 2024-09-15 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contactformlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 9, 15, 6, 36, 20, 667085, tzinfo=datetime.timezone.utc))),
                ('content', models.TextField()),
            ],
        ),
    ]
