# Generated by Django 5.1 on 2024-09-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='Company_name',
            field=models.CharField(max_length=255),
        ),
    ]
