# Generated by Django 5.1 on 2024-09-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_generalinfo_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinfo',
            old_name='Company_name',
            new_name='company_name',
        ),
    ]
